services:
  cinema-db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    container_name: postgres-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinemadb
    command: ["postgres", "-c", "wal_level=logical"]
    volumes:
      - cinemadb_data:/var/lib/postgresql/data

  cinema-backend:
    image: arcturs/cinema_backend
    platform: linux/amd64
    container_name: cinema-backend
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      DATABASE_HOST: cinema-db
      DATABASE_PORT: 5432
      DATABASE_NAME: cinemadb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - cinema-db
  
  cinema-frontend:
    image: arcturs/cinema_frontend
    platform: linux/amd64
    container_name: cinema-frontend
    ports:
      - "3000:80"
    depends_on:
      - cinema-backend

volumes:
  cinemadb_data:
