- name: Установка unzip
  apt:
    name:
      - unzip
    update_cache: yes

- name: Создание директории для проекта
  file:
    path: "{{ project_dir }}"
    state: directory
    mode: 0777

- name: Копирование архива проекта на сервер
  copy:
    src: "{{ archive_path }}"
    dest: "~/devops-cinema.zip"
    mode: 0644

- name: Распаковка архива
  unarchive:
    src: "~/devops-cinema.zip"
    dest: "{{ project_dir }}"
    remote_src: yes

#- name: Create namespace
#  community.kubernetes.k8s:
#    api_version: v1
#    kind: Namespace
#    name: cinema-app
#    state: present
#
#- name: Apply DB manifests
#  community.kubernetes.k8s:
#    state: present
#    namespace: cinema-app
#    src: "{{ role_path }}/files/manifests/db/{{ item }}"
#  loop:
#    - pvc.yaml
#    - deployment.yaml
#    - service.yaml
#
#- name: Apply Backend manifests
#  community.kubernetes.k8s:
#    state: present
#    namespace: cinema-app
#    src: "{{ role_path }}/files/manifests/backend/{{ item }}"
#  loop:
#    - deployment.yaml
#    - service.yaml
#    - hpa.yaml
#
#- name: Apply Frontend manifests
#  community.kubernetes.k8s:
#    state: present
#    namespace: cinema-app
#    src: "{{ role_path }}/files/manifests/frontend/{{ item }}"
#  loop:
#    - deployment.yaml
#    - service.yaml