global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "kube-state-metrics"
    static_configs:
      - targets: [ "158.160.157.207:8082" ]

  - job_name: "node-exporter"
    static_configs:
      - targets: [ "158.160.157.207:30100" ]

  - job_name: 'cinema-backend'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [ __meta_kubernetes_pod_label_app ]
        regex: cinema-backend
        action: keep
      - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_scrape ]
        action: keep
        regex: true
      - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_path ]
        action: replace
        target_label: /actuator/prometheus