global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "kube-state-metrics"
    static_configs:
      - targets: [ "158.160.157.207:30083" ]

  - job_name: "node-exporter"
    static_configs:
      - targets: [ "158.160.157.207:30100" ]

  - job_name: 'cinema-backend'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [ __meta_kubernetes_pod_label_app ]
        action: keep
        regex: cinema-backend
      - source_labels: [ __address__, __meta_kubernetes_pod_container_port_number ]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [ ]
        target_label: __metrics_path__
        replacement: /actuator/prometheus