global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "kube-state-metrics"
    static_configs:
      - targets: [ "158.160.157.207:8082" ]

  - job_name: "node-exporter"
    static_configs:
      - targets: [ "158.160.157.207:30100" ]

  - job_name: 'cinema-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "158.160.157.207:30002" ]