apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinema-db
  template:
    metadata:
      labels:
        app: cinema-db
    spec:
      containers:
        - name: postgres
          image: postgres:15.1-alpine
          securityContext:
            runAsUser: 999
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: cinemadb
          ports:
            - containerPort: 5432
          command: ["postgres", "-c", "wal_level=logical"]
          volumeMounts:
            - name: cinemadb-storage
              mountPath: /mnt/data
      volumes:
        - name: cinemadb-storage
          persistentVolumeClaim:
            claimName: cinemadb-data-pvc