apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinema-db
  template:
    metadata:
      labels:
        app: cinema-db
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      initContainers:
        - name: init-db
          image: postgres:15.1-alpine
          securityContext:
            runAsUser: 999
          command:
            - "sh"
            - "-c"
            - |
              if [ -z "$(ls -A /var/lib/postgresql/data)" ]; then
                echo "Инициализация базы данных..."
                initdb -D /var/lib/postgresql/data
                echo "wal_level = logical" >> /var/lib/postgresql/data/postgresql.conf
              fi
          volumeMounts:
            - name: cinemadb-storage
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: postgres:15.1-alpine
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: cinemadb
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: cinemadb-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: cinemadb-storage
          persistentVolumeClaim:
            claimName: cinemadb-data-pvc