apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinema-db
  template:
    metadata:
      labels:
        app: cinema-db
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      initContainers:
        - name: fix-data-dir
          image: alpine:3.18
          command: [ "sh", "-c", "mkdir -p /var/lib/postgresql/data && chown -R 999:999 /var/lib/postgresql/data" ]
          volumeMounts:
            - name: cinemadb-storage
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: postgres:15.1-alpine
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: cinemadb
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: cinemadb-storage
              mountPath: /var/lib/postgresql/data
          command: [ "postgres", "-c", "wal_level=logical" ]
      volumes:
        - name: cinemadb-storage
          persistentVolumeClaim:
            claimName: cinemadb-data-pvc