apiVersion: v1
kind: PersistentVolume
metadata:
  name: cinemadb-data-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  local:
    path: /var/lib/postgresql/data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fv4f3sh3tpuubt58232j