apiVersion: v1
kind: PersistentVolume
metadata:
  name: cinemadb-data-pv
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data