apiVersion: v1
kind: PersistentVolume
metadata:
  name: cinemadb-data-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  local:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce