apiVersion: v1
kind: PersistentVolume
metadata:
  name: cinemadb-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  hostPath:
    path: /mnt/data/pg
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fv4f3sh3tpuubt58232j