- name: Install dependencies
  apt:
    name:
      - git
    state: present
    update_cache: yes

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - non

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb [trusted=yes] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /
    state: present
    filename: kubernetes.lis

- name: Install Kubernetes binaries
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted

- name: Create Master Node
  include_tasks: master-server.yml