- name: Логин в DockerHub
  community.docker.docker_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_password }}"

- name: Сборка и запуск docker-compose
  command: docker compose up -d
  args:
    chdir: "{{ project_dir }}"

- name: Публикация образов на DockerHub
  shell: |
    docker compose build
    docker compose push
  args:
    chdir: "{{ project_dir }}"