archive_path: "~/devops-cinema.zip"         # Путь до архива на локальной машине
project_dir: "devops-cinema"                # Папка на ВМ после распаковки
dockerhub_username: "arcturs"               # <-- поменяй на свой логин
dockerhub_password: <dockerhub_password>