apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  type: NodePort  # Для доступа извне кластера
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 8082
  selector:
    app.kubernetes.io/name: kube-state-metrics