apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cinema-backend-metrics
  labels:
    app: cinema-backend
spec:
  selector:
    app: cinema-backend
  endpoints:
    - name: metric