apiVersion: v1
kind: Service
metadata:
  name: cinema-backend-metrics
  labels:
    app: cinema-backend
spec:
  type: NodePort
  clusterIP: None
  selector:
    app: cinema-backend
  ports:
    - name: metrics
      port: 8081
      targetPort: 8081
      nodePort: 30002