apiVersion: v1
kind: Service
metadata:
  name: cinema-backend
spec:
  type: LoadBalancer
  selector:
    app: cinema-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30001
    - name: actuator
      port: 8081
      targetPort: 8081
      nodePort: 30002