apiVersion: v1
kind: Service
metadata:
  name: cinema-backend
spec:
  type: ClusterIP
  selector:
    app: cinema-backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001