spring:
  application.name: backend
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: classpath:db.changelog/changelog-master.yaml

server:
  port: 8080

management:
  server.port: 8081
  endpoint:
    health.access: read_only
    info.access: read_only
    metrics.access: unrestricted
    prometheus.access: unrestricted
    loggers.access: read_only
  endpoints.web.exposure.include: health,info,prometheus,metrics,loggers
