- name: Развертывание проекта из архива и выкладка в DockerHub
  hosts: all
  become: true
  vars:
    archive_path: "~/devops-cinema.zip"        # Путь до архива на локальной машине
    project_dir: "devops-cinema" # Папка на ВМ после распаковки

  tasks:
    - name: Установка unzip
      apt:
        name:
          - unzip
        update_cache: yes

    - name: Создание директории для проекта
      file:
        path: "{{ project_dir }}"
        state: directory
        owner: sertitan
        group: sertitan
        mode: 0755

    - name: Копирование архива проекта на сервер
      copy:
        src: "{{ archive_path }}"
        dest: "/tmp/devops-cinema.zip"
        mode: 0644

    - name: Распаковка архива
      unarchive:
        src: "/tmp/devops-cinema.zip"
        dest: "{{ project_dir }}"
        remote_src: yes

    - name: Сборка и запуск docker-compose
      command: docker compose up -d
      args:
        chdir: "{{ project_dir }}"
