- name: Развертывание проекта из архива
  hosts: vm
  become: true
  roles:
    - cinema-app

#- name: Установка Docker на ВМ
#  hosts: vm
#  become: true
#  roles:
#    - docker-install

- name: Запуск приложения в Docker и деплой в Docker Hub
  hosts: all
  become: true
  roles:
    - docker-deploy